name: End-to-end tests 🧪
on: [push] #A cada push para o repositório remoto, esse job será disparado
jobs:
  cypress-run:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout #p/ o github baixar no workspace do githubAction o código do projeto
        uses: actions/checkout@v2
      # Install NPM dependencies, cache them correctly
      # and run all Cypress tests
      - name: Cypress run
        uses: cypress-io/github-action@v2